[providers]
providers = ['java']

[phases.setup]
nixPkgs = ['maven', 'openjdk17']

[phases.build]
cmds = ['cd backend && mvn clean package -DskipTests']

[start]
cmd = 'java -jar backend/target/govshield-1.0.0.jar'
