spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/govshield?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:root}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:root}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:${SERVER_PORT:8080}}
logging.level.root=INFO
